config/routes.rb
Rails.application.routes.draw do
  resources :usernames
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get "mi_primera_vista",to:"welcome#index"
get "mi_segunda_vista",to:"welcome#index1"
get "mi_tercera_vista",to:"welcome#mi_pagina"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/username.rb
class Username < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/usernames_controller.rb
class UsernamesController < ApplicationController
  before_action :set_username, only: [:show, :edit, :update, :destroy]

  # GET /usernames
  # GET /usernames.json
  def index
    @usernames = Username.all
  end

  # GET /usernames/1
  # GET /usernames/1.json
  def show
  end

  # GET /usernames/new
  def new
    @username = Username.new
  end

  # GET /usernames/1/edit
  def edit
  end

  # POST /usernames
  # POST /usernames.json
  def create
    @username = Username.new(username_params)

    respond_to do |format|
      if @username.save
        format.html { redirect_to @username, notice: 'Username was successfully created.' }
        format.json { render :show, status: :created, location: @username }
      else
        format.html { render :new }
        format.json { render json: @username.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usernames/1
  # PATCH/PUT /usernames/1.json
  def update
    respond_to do |format|
      if @username.update(username_params)
        format.html { redirect_to @username, notice: 'Username was successfully updated.' }
        format.json { render :show, status: :ok, location: @username }
      else
        format.html { render :edit }
        format.json { render json: @username.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usernames/1
  # DELETE /usernames/1.json
  def destroy
    @username.destroy
    respond_to do |format|
      format.html { redirect_to usernames_url, notice: 'Username was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_username
      @username = Username.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def username_params
      params.require(:username).permit(:string)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
def index
def index1
def mi_pagina
end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/usernames_helper.rb
module UsernamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/usernames/_form.html.erb
<%= form_with(model: username, local: true) do |form| %>
  <% if username.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(username.errors.count, "error") %> prohibited this username from being saved:</h2>

      <ul>
      <% username.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :string %>
    <%= form.text_field :string %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usernames/edit.html.erb
<h1>Editing Username</h1>

<%= render 'form', username: @username %>

<%= link_to 'Show', @username %> |
<%= link_to 'Back', usernames_path %>

app/views/usernames/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usernames</h1>

<table>
  <thead>
    <tr>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usernames.each do |username| %>
      <tr>
        <td><%= username.string %></td>
        <td><%= link_to 'Show', username %></td>
        <td><%= link_to 'Edit', edit_username_path(username) %></td>
        <td><%= link_to 'Destroy', username, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Username', new_username_path %>

app/views/usernames/new.html.erb
<h1>New Username</h1>

<%= render 'form', username: @username %>

<%= link_to 'Back', usernames_path %>

app/views/usernames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>String:</strong>
  <%= @username.string %>
</p>

<%= link_to 'Edit', edit_username_path(@username) %> |
<%= link_to 'Back', usernames_path %>

app/views/welcome/index.html.erb
Mi primera vista en ruby rails

app/views/welcome/index1.html.erb
Esta es mi segunda vista jijijijjijij lo hice.... ahy voy entiendiendo

app/views/welcome/mi_pagina.html.erb
Esta es otra pagina de prueba cheverita